import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'

const nunito = Nunito_Sans({
  subsets: ['latin'],

  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],

  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Memo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={nunito.className}>
        {children}
        <Toaster position='top-center' />
      </body>
    </html>
  )
}
