import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { RouteChangeProvider } from "@/components/ui/route-change-provider";

import Providers from "@/lib/providers";

const nunito = Nunito_Sans({
  subsets: ["latin"],

  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],

  display: "swap",
});

export const metadata: Metadata = {
  title: "Memo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Providers>
          <RouteChangeProvider>{children}</RouteChangeProvider>
        </Providers>
      </body>
    </html>
  );
}
